# Generated by Django 3.0.4 on 2020-04-06 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv_manage', '0003_auto_20200403_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='picture',
            field=models.ImageField(default='default.jpg', upload_to='item_pics'),
        ),
    ]
